### ISSUE TITLE
User guide review for fresh eyes

### ISSUE THREAD

**Issue by hangfei** [linkedin/feathr#160]
We just added quite a few wikis, and tutorials. It's good to have some new users that have never used Feathr try it out.
Review the user guide by new users so we know if it's easy to understand and onboard(from easy to hard). 

- Read the documentations to see if it's easy enough to understand
- If there is something not well-explained or missing, try to fix them or raise a issue with us.

Here are the documentations:
https://github.com/linkedin/feathr/blob/main/docs/concepts/feathr-concepts-for-beginners.md

https://github.com/linkedin/feathr/blob/main/docs/concepts/feathr-capabilities.md

https://github.com/linkedin/feathr/blob/main/docs/concepts/feature-definition.md

https://github.com/linkedin/feathr/blob/main/docs/concepts/feature-generation.md

https://github.com/linkedin/feathr/blob/main/docs/concepts/feature-join.md

https://github.com/linkedin/feathr/blob/main/docs/concepts/point-in-time-join.md

**Comment by ahlag** [comment]
@hangfei 
Just curious. Is joining different column names as the join key in the example intentional?
https://github.com/linkedin/feathr/blob/3b6449155114aca385608c187137fac78255ec0f/docs/concepts/feature-join.md?plain=1#L18
https://github.com/linkedin/feathr/blob/3b6449155114aca385608c187137fac78255ec0f/docs/concepts/feature-join.md?plain=1#L27

**Comment by hangfei** [comment]
Hi Chang Yong,

Good question.

Here user_id and id all refers to the same thing: a user's ID. But in reality, due to various reasons, sometimes dataset may use different column names. So this is demonstrate that how people can join different datasets if their column name is different but the meaning is the same.

I believe we should add a feature definition to this file so it's more obvious.

Also the feature query key is wrong:

feature_query = FeatureQuery(

    feature_list=["f_location_avg_fare"], key=location_id)

the location_id should be id.

Thanks,
Hangfei
________________________________
