### ISSUE TITLE
Pretty-print the features produced by buildFeatures and submit job

### ISSUE THREAD

**Issue by hangfei** [linkedin/feathr#163]
Provide a pretty-print flag in buildFeautre(https://github.com/linkedin/feathr/blob/main/feathr_project/feathr/client.py#L213). If it's true, then print the features that are constructed by buildFeature in pretty-print form.

Same for get_offline_feature: https://github.com/linkedin/feathr/blob/main/feathr_project/feathr/client.py#L392 and https://github.com/linkedin/feathr/blob/main/feathr_project/feathr/client.py#L514.

**Comment by ahlag** [comment]
@hangfei 
How will this be tested?
