### ISSUE TITLE
CI test does not work as expected

### ISSUE THREAD

**Issue by xiaoyongzhu** [linkedin/feathr#174]
There are two issues:
1. After @jainr 's PR, the CI code in main branch will not run
2. For forked repository, the test will only run once and won't run after further changes (reported by @windoze )
3. more comments below by other folks

**Comment by Yuqing-cat** [comment]
My case is you need to unlabel and relabel the PR as "**safe to test**" to trigger the right action. And it will trigger a normal GitHub action (no secret) after further changes, which causes some fail records in PR.

**Comment by jainr** [comment]
https://github.com/linkedin/feathr/pull/239
