### ISSUE TITLE
Add validation for feature name

### ISSUE THREAD

**Issue by hangfei** [linkedin/feathr#227]
Feature name should follow some naming conventions and rules otherwise it will break certain underlying engine, like spark or storage.

**Comment by lhayhurst** [comment]
As per the comment on line 18 of setup.py:

>Only alphabet, numbers, and '_' are allowed in the name. It can not start with numbers. Note that '.' is NOT ALLOWED!

Are these all the validation rules needed?

**Comment by lhayhurst** [comment]
I banged out a PR on my fork; please let me know if this is the sort of validation you were thinking of? Of so, I can issue a PR against the main repo.

 https://github.com/lhayhurst/feathr/pull/1

**Comment by lhayhurst** [comment]
@hangfei  @xiaoyongzhu  Hello, just bumping this issue for visibility. Cheers

**Comment by hangfei** [comment]
Hi @lhayhurst , the notifications are buried in my mailbox so i didn't see it earlier. Sry about the late reply.

Thanks for your interest on the project!

For the issue, yes. that's the only rules right now.

The PR looks good to me and only some minor comments.

@chinmaytredence  who are interested on leveraging the feature name validation work.

**Comment by lhayhurst** [comment]
@hangfei   @chinmaytredence  PR is up https://github.com/linkedin/feathr/pull/258/files

**Comment by chinmaytredence** [comment]
@lhayhurst thanks for this contribution.
@hangfei this would help us for create entity api. I think the exception message could also be sent as response while exposing through fast api

**Comment by hangfei** [comment]
@chinmaytredence Yeah. I will make sure this is incorporated into our API side. cc: @YihuiGuo

**Comment by xiaoyongzhu** [comment]
closed because of https://github.com/linkedin/feathr/pull/258/files
