### ISSUE TITLE
Mac developer install: a howto

### ISSUE THREAD

**Issue by lhayhurst** [linkedin/feathr#234]
Hello, I was able to install the project on a mac with a few tweaks to the [python_dev_guide.md](docs/dev_guide/python_dev_guide.md).

After making the virtualenv and running `python3 -m pip install -e .`, I got this error mesage: 

```
 fatal error: 'librdkafka/rdkafka.h' file not found
    #include <librdkafka/rdkafka.h>
             ^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
```

Here's the fix:

0) install [brew](https://brew.sh/)
1) install `librdkafka` by running the command `brew install librdkafka` 
2) run `brew info librdkafka`, take note of the library install path (for example, "/opt/homebrew/Cellar/librdkafka/1.8.2/include"), 
3) run `export C_INCLUDE_PATH=$LIBRDKAFKA_INCLUDE_PATH`, where `$LIBRDKAFKA_INCLUDE_PATH` is the include path found in step 2.
4) Run `python3 -m pip install -e .`

Happy to submit a PR with an update to the `python_dev_guide.md` if you think this info would be helpful to others; otherwise, I can close this ticket! Cheers

**Comment by xiaoyongzhu** [comment]
@lhayhurst Would be great if you can open a doc PR fixing this! Appreciate for the help!

**Comment by lhayhurst** [comment]
@xiaoyongzhu , [here's a small PR](https://github.com/linkedin/feathr/pull/244), cheers

**Comment by lhayhurst** [comment]
PR is merged
