### ISSUE TITLE
Should feathr_project/setup.py have `pytest`?

### ISSUE THREAD

**Issue by lhayhurst** [linkedin/feathr#235]
I think the dev guide (docs/dev_guide/python_dev_guide.md) assumes that `pytest` is installed.

```
## Integration Test

Run `pytest` in this folder to kick off the integration test. The integration test will test the creation of feature dataset, the materialization to online storage, and retrieve from online storage, as well as the CLI. It usually takes 5 ~ 10 minutes. It needs certain keys for cloud resources.
```

results in `pytest not found`. 

Adding pytest in the `install_requires` of  `feathr_project/setup.py` fixed this for me. I can submit a PR if you think pytest should be added to the setup. 

Cheers

**Comment by xiaoyongzhu** [comment]
I guess putting it into `install_requires` might install it for everyone and maybe you can put a PR in the doc? Thanks!

**Comment by lhayhurst** [comment]
Hi, I see your point, I guess its fine the way it works now. I'l close this ticket, cheers.
