### ISSUE TITLE
deployment failed at "REDIS_PASSWORD" step, see image

### ISSUE THREAD

**Issue by truehand** [linkedin/feathr#238]
![image](https://user-images.githubusercontent.com/7256611/167473252-53fea33b-0fa2-4df0-91da-e2ad33005d8c.png)

**Comment by truehand** [comment]
This error is consistent across different regions I tried

**Comment by xiaoyongzhu** [comment]
Thanks for this! This should be fixed by https://github.com/linkedin/feathr/pull/233
