### ISSUE TITLE
Synapse notebook support

### ISSUE THREAD

**Issue by xiaoyongzhumsft** [linkedin/feathr#25]
Currently Synapse notebook is not supported since current assumption is that users run `feathr init` in the shell environment. However, Synapse notebook doesn't support doing so.

To make Synapse notebook support, I suggest adding an API in the `FeathrClient` class which can initialize a feathr workspace from python API.

Implementation wise, it will be like adding some API in this file (https://github.com/linkedin/feathr/blob/main/feathr_project/feathr/client.py) referencing some of the CLI functions (https://github.com/linkedin/feathr/blob/main/feathr_project/feathrcli/cli.py)

**Comment by xiaoyongzhu** [comment]
Closed as it's working now.
