### ISSUE TITLE
Feathr UI: Lineage nodes to be alike Purview

### ISSUE THREAD

**Issue by chinmaytredence** [linkedin/feathr#255]
Currently the Lineage UI in the UI directory is showing the connected features. Do we have any plan to make those nodes as functional as Purview gives currently ?

**Comment by blrchen** [comment]
loop @xiaoyongzhu for discussion.

**Comment by xiaoyongzhu** [comment]
I think as long as we can click the node and navigate to the corresponding item it should be fine @chinmaytredence

**Comment by chinmaytredence** [comment]
@xiaoyongzhu thanks for the thoughts. need one clarity, the node click event will navigate to purview portal or it will display the definition and properties on the same ui page ?

**Comment by blrchen** [comment]
> @xiaoyongzhu thanks for the thoughts. need one clarity, the node click event will navigate to purview portal or it will display the definition and properties on the same ui page ?

It will be redirected to feature details page in same ui. The reason is other feature registry provider like sql does not have purview portal.

**Comment by chinmaytredence** [comment]
@blrchen thanks for confirming. I think just the node click event is pending to route to the details page of the feature.
