### ISSUE TITLE
Feathr UI feedback

### ISSUE THREAD

**Issue by blrchen** [linkedin/feathr#272]
This issue is opened for tracking feedbacks received for Feathr UI so far

## Preview site

https://brave-moss-045d2ce00.1.azurestaticapps.net

## Feedbacks

- [x] Display feature key in details page
- [ ] Have a quick start (preview mode)
- [ ] Add a summary homepage
- The project that this person has worked on or browsed 
- Or biggest/most popular project if this person has worked on no projects 
- [x] Add an Avatar with name initials on the right near the logout button 
- [x] Put a “Under construction” sign for jobs page
- [x] Add a feature monitoring page and add “Under construction” sign 
- [x] [Lineage] Highlight the feature I clicked
- [x] [Lineage] Color the features in the same project as this feature with one color. And the other projects with different color. Also add color encoding illustrations
- [x] [Lineage] Embed the page in the feature sub tab
- [x] [Lineage] Remove unused Lineage (i.e. Atlas Process) in the UI
- [x] [Lineage] When click on the lineage blocks, jump to the corresponding feature page
- [x] [Lineage] After i clicked a certain figure, can we highlight the feature where i clicked?
- [x] [Lineage] Slightly move the graph in the middle.
- [ ] [Lineage] Add tooltip or explanation text for what each color means
- [x] [Lineage] Add a way to click the feature and open the detail page.
- [ ] For source page, display the projects that this person has worked on
- [ ] For feature page, display the projects that this person has worked on
- [x] Make the search bar work 
- [x] Show the “tag” part 
- [ ] Show the users who updated the feature, and what’s the updated time 
- [x] All the contents in the feature page (like [here](https://ms.web.purview.azure.com/resource/feathrazuretest3-purview1/main/catalog/entity?guid=9c2dc6e6-a665-4bf4-b02f-0c327987c599&section=properties&feature.tenant=72f988bf-86f1-41af-91ab-2d7cd011db47)) 
- [ ] Source should be clickable and have its own page like features. The source page should display all features belong to this source of a project.

**Comment by xiaoyongzhu** [comment]
Can we also add this one?

- Remove unused Lineage (i.e. Atlas Process) in the UI

**Comment by blrchen** [comment]
> Could we add: source should be clickable and have its own page like features. The source page should display all features belong to this source of a project.

Thanks for feedback, this has been appended to the list in description.

**Comment by blrchen** [comment]
> Can we also add this one?
> 
> * Remove unused Lineage (i.e. Atlas Process) in the UI

Thanks for feedback, this has been appended to the list in description.

**Comment by xiaoyongzhu** [comment]
Consider adding metadata health and owners information
