### ISSUE TITLE
Azure job url is not set and thus not logged correctly during error.

### ISSUE THREAD

**Issue by bozhonghu** [linkedin/feathr#326]
It seems like the job url for the azure job is not set. The error log here does not work: https://github.com/linkedin/feathr/blob/85c2bf50337bdd32f3e63bb521d9aa55f994736c/feathr_project/feathr/_synapse_submission.py#L138
```
logger.error("Feathr job has failed. Please visit this page to view error message: {}", self.job_url)
E               AttributeError: '_FeathrSynapseJobLauncher' object has no attribute 'job_url'
feathr_project/feathr/_synapse_submission.py:138: AttributeError
```
^ is the error I see. 
It seems like the variable self.job_url is not set anywhere

**Comment by windoze** [comment]
Fixed in #327
