### ISSUE TITLE
Azure only?

### ISSUE THREAD

**Issue by boniek83** [linkedin/feathr#331]
It's not quite clear to me if Feathr is Azure only (meaning no other clouds or on-prem is supported) or you guys support Azure only deployments (meaning you can deploy it anywhere but you focus on Azure). Can somebody clarify?

**Comment by xiaoyongzhu** [comment]
Feathr is NOT Azure only, like you can use it to ingest data from S3, use Databricks on AWS to run thru the job, etc. I.e. other clouds are supported (on-prem might be a bit hard and need more work, and to be honest we only focus on cloud only), and you can deploy it in major cloud providers.
