### ISSUE TITLE
Binder Notebook doesn't work

### ISSUE THREAD

**Issue by Yuqing-cat** [linkedin/feathr#359]
![image](https://user-images.githubusercontent.com/26561033/173536660-d562e858-cf46-43db-bbf1-eeb6490722ea.png)

![image](https://user-images.githubusercontent.com/26561033/173536990-b36beea9-0b86-435b-ae18-05c5690a0f2c.png)

![image](https://user-images.githubusercontent.com/26561033/173537375-a0b87fb2-3833-444e-aa93-22ef28a09082.png)

**Comment by xiaoyongzhu** [comment]
this should be working now.

**Comment by inchiosa** [comment]
FYI, today I noticed that launching the Binder notebook failed on the first attempt, but it succeeded on the second attempt.
