### ISSUE TITLE
Feathr Documentation Table Render Issue with "Just the Doc"

### ISSUE THREAD

**Issue by Yuqing-cat** [linkedin/feathr#377]
https://linkedin.github.io/feathr/how-to-guides/feathr-configuration-and-env.html
![image](https://user-images.githubusercontent.com/26561033/174059258-4230d28c-e91b-4303-8054-542cdff65973.png)

It looks good in GitHub:
![image](https://user-images.githubusercontent.com/26561033/174061205-8aff3ceb-0028-4905-a371-afab7aaee93d.png)

**Comment by Yuqing-cat** [comment]
Acceptance Criteria:
1. Fix the table render problem 
2. Update the doc link from "https://github.com/linkedin/feathr/blob/41e7496b38c43af6d7f8f1de842f657b27840f6d/docs/how-to-guides/feathr-configuration-and-env.md#a-note-on-using-azure-key-vault-to-store-credentials" to "https://linkedin.github.io/feathr/how-to-guides/feathr-configuration-and-env.html"

**Comment by xiaoyongzhu** [comment]
confirm it's closed: 

<img width="986" alt="image" src="https://user-images.githubusercontent.com/1185090/178106437-f5791147-f9e5-4cf3-8497-d9fc854a9544.png">

Feel the root cause is the original table format isn't using a very standard way in markdown and justthedocs might not understand it.
