### ISSUE TITLE
Implement broken link detect tools in docs

### ISSUE THREAD

**Issue by Yuqing-cat** [linkedin/feathr#393]
background: https://github.com/linkedin/feathr/pull/392

As the volume of documentations grows, it hard to detect broken links throughout them manually. 
Some test strategy should be implemented to guarantee the doc quality.

**Comment by ahlag** [comment]
@Yuqing-cat 
I have tested running `pytest --check-links --check-links-cache` in `feathr/docs`. Would you like to implement this in Github Actions?

Got the following output.
```
===================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/changyonglik/Desktop/opensource/feathr/docs
plugins: check-links-0.7.1
collected 168 items

README.md ........F...............                                                                                                                                                       [ 14%]
quickstart_databricks.md ....                                                                                                                                                            [ 16%]
quickstart_synapse.md ............F.                                                                                                                                                     [ 23%]
concepts/feathr-concepts-for-beginners.md .....                                                                                                                                          [ 26%]
concepts/feature-definition.md .......                                                                                                                                                   [ 29%]
concepts/feature-generation.md ........                                                                                                                                                  [ 33%]
concepts/feature-join.md ...                                                                                                                                                             [ 35%]
concepts/point-in-time-join.md .                                                                                                                                                         [ 36%]
design_docs/feature_registry_abstraction.md ....                                                                                                                                         [ 38%]
dev_guide/cloud_integration_testing.md F.                                                                                                                                                [ 39%]
dev_guide/cloud_resource_provision.md F...F..F...                                                                                                                                        [ 45%]
dev_guide/doc_guide.md ..                                                                                                                                                                [ 47%]
dev_guide/feathr_overall_release_guide.md .....                                                                                                                                          [ 50%]
dev_guide/publish_to_maven.md ....                                                                                                                                                       [ 52%]
dev_guide/python_dev_guide.md ....                                                                                                                                                       [ 54%]
dev_guide/python_package_release.md F..                                                                                                                                                  [ 56%]
dev_guide/scala_dev_guide.md ......                                                                                                                                                      [ 59%]
dev_guide/update_python_docs.md ....F                                                                                                                                                    [ 62%]
how-to-guides/azure-deployment.md ................                                                                                                                                       [ 70%]
how-to-guides/build-and-push-feathr-registry-docker-image.md .F                                                                                                                          [ 72%]
how-to-guides/deploy-feathr-api-as-webapp.md .......                                                                                                                                     [ 76%]
how-to-guides/expression-language.md ..                                                                                                                                                  [ 77%]
how-to-guides/feathr-configuration-and-env.md ..........                                                                                                                                 [ 81%]
how-to-guides/feathr-job-configuration.md ...                                                                                                                                            [ 82%]
how-to-guides/local-feature-testing.md .                                                                                                                                                 [ 83%]
how-to-guides/troubleshoot-feature-definition.md .                                                                                                                                       [ 83%]
samples/customer360/Customer360.ipynb ........                                                                                                                                           [ 88%]
samples/databricks/databricks_quickstart_nyc_taxi_driver.ipynb ......

=========================================================================================== FAILURES ===========================================================================================
________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/README.md: https://linkedin.github.io/feathr/how-to-guides/streaming_source_ingestion.html _________________________
https://linkedin.github.io/feathr/how-to-guides/streaming_source_ingestion.html: 404: Not Found
________________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/quickstart_synapse.md: ../how-to-guides/azure-deployment.md ________________________________________
../how-to-guides/azure-deployment.md: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/../how-to-guides/azure-deployment.md
__________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_integration_testing.md: ../.github/workflows/scala.yml ___________________________________
../.github/workflows/scala.yml: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../.github/workflows/scala.yml
____________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md: ../how-to-guides/deploy.json ____________________________________
../how-to-guides/deploy.json: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../how-to-guides/deploy.json
____________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md: ../how-to-guides/deploy.json ____________________________________
../how-to-guides/deploy.json: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../how-to-guides/deploy.json
_________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md: ../how-to-guides/deployFeathr.ps1 __________________________________
../how-to-guides/deployFeathr.ps1: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../how-to-guides/deployFeathr.ps1
_______________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/python_package_release.md: https://pypi.org/manage/project/feathr/ ________________________________
https://pypi.org/manage/project/feathr/: 404: Not Found
_____________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/update_python_docs.md: https://xxx.readthedocs.io/en/latest/feathr.html _____________________________
https://xxx.readthedocs.io/en/latest/feathr.html: 404: Not Found
___________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/how-to-guides/build-and-push-feathr-registry-docker-image.md: https://localhost:3000 ____________________________
https://localhost:3000: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10a8ad6a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
======================================================================================= warnings summary =======================================================================================
../../../../../../usr/local/lib/python3.9/site-packages/nbconvert/exporters/html.py:100
  /usr/local/lib/python3.9/site-packages/nbconvert/exporters/html.py:100: DeprecationWarning: 'contextfilter' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
    def markdown2html(self, context, source):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================================================================== short test summary info ====================================================================================
FAILED README.md::/Users/changyonglik/Desktop/opensource/feathr/docs/README.md <a href=https://linkedin.github.io/feathr/how-to-guides/streaming_source_ingestion.html>
FAILED quickstart_synapse.md::/Users/changyonglik/Desktop/opensource/feathr/docs/quickstart_synapse.md <a href=../how-to-guides/azure-deployment.md>
FAILED dev_guide/cloud_integration_testing.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_integration_testing.md <a href=../.github/workflows/scala.yml>
FAILED dev_guide/cloud_resource_provision.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md <a href=../how-to-guides/deploy.json>
FAILED dev_guide/cloud_resource_provision.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md <a href=../how-to-guides/deploy.json>
FAILED dev_guide/cloud_resource_provision.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md <a href=../how-to-guides/deployFeathr.ps1>
FAILED dev_guide/python_package_release.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/python_package_release.md <a href=https://pypi.org/manage/project/feathr/>
FAILED dev_guide/update_python_docs.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/update_python_docs.md <a href=https://xxx.readthedocs.io/en/latest/feathr.html>
FAILED how-to-guides/build-and-push-feathr-registry-docker-image.md::/Users/changyonglik/Desktop/opensource/feathr/docs/how-to-guides/build-and-push-feathr-registry-docker-image.md <a href=https://localhost:3000>
=========================================================================== 9 failed, 159 passed, 1 warning in 2.28s ===========================================================================
```

**Comment by blrchen** [comment]
> @Yuqing-cat I have tested running `pytest --check-links --check-links-cache` in `feathr/docs`. Would you like to implement this in Github Actions?
> 
> Got the following output.
> 
> ```
> ===================================================================================== test session starts ======================================================================================
> platform darwin -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
> rootdir: /Users/changyonglik/Desktop/opensource/feathr/docs
> plugins: check-links-0.7.1
> collected 168 items
> 
> README.md ........F...............                                                                                                                                                       [ 14%]
> quickstart_databricks.md ....                                                                                                                                                            [ 16%]
> quickstart_synapse.md ............F.                                                                                                                                                     [ 23%]
> concepts/feathr-concepts-for-beginners.md .....                                                                                                                                          [ 26%]
> concepts/feature-definition.md .......                                                                                                                                                   [ 29%]
> concepts/feature-generation.md ........                                                                                                                                                  [ 33%]
> concepts/feature-join.md ...                                                                                                                                                             [ 35%]
> concepts/point-in-time-join.md .                                                                                                                                                         [ 36%]
> design_docs/feature_registry_abstraction.md ....                                                                                                                                         [ 38%]
> dev_guide/cloud_integration_testing.md F.                                                                                                                                                [ 39%]
> dev_guide/cloud_resource_provision.md F...F..F...                                                                                                                                        [ 45%]
> dev_guide/doc_guide.md ..                                                                                                                                                                [ 47%]
> dev_guide/feathr_overall_release_guide.md .....                                                                                                                                          [ 50%]
> dev_guide/publish_to_maven.md ....                                                                                                                                                       [ 52%]
> dev_guide/python_dev_guide.md ....                                                                                                                                                       [ 54%]
> dev_guide/python_package_release.md F..                                                                                                                                                  [ 56%]
> dev_guide/scala_dev_guide.md ......                                                                                                                                                      [ 59%]
> dev_guide/update_python_docs.md ....F                                                                                                                                                    [ 62%]
> how-to-guides/azure-deployment.md ................                                                                                                                                       [ 70%]
> how-to-guides/build-and-push-feathr-registry-docker-image.md .F                                                                                                                          [ 72%]
> how-to-guides/deploy-feathr-api-as-webapp.md .......                                                                                                                                     [ 76%]
> how-to-guides/expression-language.md ..                                                                                                                                                  [ 77%]
> how-to-guides/feathr-configuration-and-env.md ..........                                                                                                                                 [ 81%]
> how-to-guides/feathr-job-configuration.md ...                                                                                                                                            [ 82%]
> how-to-guides/local-feature-testing.md .                                                                                                                                                 [ 83%]
> how-to-guides/troubleshoot-feature-definition.md .                                                                                                                                       [ 83%]
> samples/customer360/Customer360.ipynb ........                                                                                                                                           [ 88%]
> samples/databricks/databricks_quickstart_nyc_taxi_driver.ipynb ......
> 
> =========================================================================================== FAILURES ===========================================================================================
> ________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/README.md: https://linkedin.github.io/feathr/how-to-guides/streaming_source_ingestion.html _________________________
> https://linkedin.github.io/feathr/how-to-guides/streaming_source_ingestion.html: 404: Not Found
> ________________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/quickstart_synapse.md: ../how-to-guides/azure-deployment.md ________________________________________
> ../how-to-guides/azure-deployment.md: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/../how-to-guides/azure-deployment.md
> __________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_integration_testing.md: ../.github/workflows/scala.yml ___________________________________
> ../.github/workflows/scala.yml: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../.github/workflows/scala.yml
> ____________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md: ../how-to-guides/deploy.json ____________________________________
> ../how-to-guides/deploy.json: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../how-to-guides/deploy.json
> ____________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md: ../how-to-guides/deploy.json ____________________________________
> ../how-to-guides/deploy.json: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../how-to-guides/deploy.json
> _________________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md: ../how-to-guides/deployFeathr.ps1 __________________________________
> ../how-to-guides/deployFeathr.ps1: No such file: /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/../how-to-guides/deployFeathr.ps1
> _______________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/python_package_release.md: https://pypi.org/manage/project/feathr/ ________________________________
> https://pypi.org/manage/project/feathr/: 404: Not Found
> _____________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/update_python_docs.md: https://xxx.readthedocs.io/en/latest/feathr.html _____________________________
> https://xxx.readthedocs.io/en/latest/feathr.html: 404: Not Found
> ___________________________ /Users/changyonglik/Desktop/opensource/feathr/docs/how-to-guides/build-and-push-feathr-registry-docker-image.md: https://localhost:3000 ____________________________
> https://localhost:3000: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10a8ad6a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
> ======================================================================================= warnings summary =======================================================================================
> ../../../../../../usr/local/lib/python3.9/site-packages/nbconvert/exporters/html.py:100
>   /usr/local/lib/python3.9/site-packages/nbconvert/exporters/html.py:100: DeprecationWarning: 'contextfilter' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
>     def markdown2html(self, context, source):
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> =================================================================================== short test summary info ====================================================================================
> FAILED README.md::/Users/changyonglik/Desktop/opensource/feathr/docs/README.md <a href=https://linkedin.github.io/feathr/how-to-guides/streaming_source_ingestion.html>
> FAILED quickstart_synapse.md::/Users/changyonglik/Desktop/opensource/feathr/docs/quickstart_synapse.md <a href=../how-to-guides/azure-deployment.md>
> FAILED dev_guide/cloud_integration_testing.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_integration_testing.md <a href=../.github/workflows/scala.yml>
> FAILED dev_guide/cloud_resource_provision.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md <a href=../how-to-guides/deploy.json>
> FAILED dev_guide/cloud_resource_provision.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md <a href=../how-to-guides/deploy.json>
> FAILED dev_guide/cloud_resource_provision.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/cloud_resource_provision.md <a href=../how-to-guides/deployFeathr.ps1>
> FAILED dev_guide/python_package_release.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/python_package_release.md <a href=https://pypi.org/manage/project/feathr/>
> FAILED dev_guide/update_python_docs.md::/Users/changyonglik/Desktop/opensource/feathr/docs/dev_guide/update_python_docs.md <a href=https://xxx.readthedocs.io/en/latest/feathr.html>
> FAILED how-to-guides/build-and-push-feathr-registry-docker-image.md::/Users/changyonglik/Desktop/opensource/feathr/docs/how-to-guides/build-and-push-feathr-registry-docker-image.md <a href=https://localhost:3000>
> =========================================================================== 9 failed, 159 passed, 1 warning in 2.28s ===========================================================================
> ```

This is awesome, copy @xiaoyongzhu

**Comment by ahlag** [comment]
@Yuqing-cat 
Yeah sure. I can start working this next week.

**Comment by ahlag** [comment]
@Yuqing-cat 
Hey, I finished early. Could you please review https://github.com/linkedin/feathr/pull/414?
This is the output that I tested on my forked repo. https://github.com/ahlag/feathr/runs/7115496370?check_suite_focus=true
