### ISSUE TITLE
Main branch ci linkcheck breaks with parse error

### ISSUE THREAD

**Issue by blrchen** [linkedin/feathr#608]
@ahlag , linkcheck ci run breaks in main branch. Here is an example link: https://github.com/linkedin/feathr/runs/8011026910?check_suite_focus=true. 

E   IndexError: list index out of range
=========================== short test summary info ============================
ERROR docs/samples/fraud_detection_demo.ipynb - IndexError: list index out of...
ERROR docs/samples/product_recommendation_demo.ipynb - IndexError: list index...
ERROR docs/samples/product_recommendation_demo_advanced.ipynb - IndexError: l...
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 2.28s ===============================
Error: Process completed with exit code 2.

This seems a parser error, could you please help take a look?

**Comment by ahlag** [comment]
@blrchen 
Please assign to me! Thanks
