### ISSUE TITLE
[BUG] materialize_features fails with Spark error: java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by blrchen** [linkedin/feathr#616]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Feathr version

All versions

### System information

Databricks runtime 10.4

### Describe the problem

Call materialize_features with redis sink, using maven jar file. The spark job in Databricks is failing with java.lang.IllegalAccessError

This seems caused by mismatch protobuf between feathr build.sbt (v3) and spark cluster (v2). 
- protobuf-java used in feathr build.sbt is 3.19.4, source:https://github.com/linkedin/feathr/blob/main/build.sbt#L42
- protobuf-java used in Azure Databricks is 2.6.1, source: https://docs.databricks.com/release-notes/runtime/10.4.html
- protobuf-java used in Azure Synpase is 2.5.0, source: https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-3-runtime

Only user who use runtime jar from maven will have impact, this issue does not occur if user uses runtime from Azure Storage which is a fat jar includes all dependencies. 

Detail logs (full log can be viewed at https://adb-1996253548709298.18.azuredatabricks.net/?o=1996253548709298#setting/clusters/0826-011329-8niddv06/driverLogs: 
`
Py4JJavaError: An error occurred while calling z:com.linkedin.feathr.offline.job.FeatureGenJob.mainWithPreprocessedDataFrame.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 13.0 failed 4 times, most recent failure: Lost task 0.3 in stage 13.0 (TID 20) (10.139.64.16 executor 1): java.lang.IllegalAccessError: tried to access field com.google.protobuf.AbstractMessage.memoizedSize from class com.linkedin.feathr.common.types.protobuf.FeatureValueOuterClass$FeatureValue
	at com.linkedin.feathr.common.types.protobuf.FeatureValueOuterClass$FeatureValue.getSerializedSize(FeatureValueOuterClass.java:1296)
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:64)
	at com.linkedin.feathr.offline.generation.outputProcessor.RedisOutputUtils$.$anonfun$getConversionFunction$2(RedisOutputUtils.scala:99)
	at com.linkedin.feathr.offline.generation.outputProcessor.RedisOutputUtils$.$anonfun$encodeDataFrame$2(RedisOutputUtils.scala:51)
	at com.linkedin.feathr.offline.generation.outputProcessor.RedisOutputUtils$.$anonfun$encodeDataFrame$2$adapted(RedisOutputUtils.scala:48)
`

### What component(s) does this bug affect?

- [ ] `Python Feathr Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [X] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API Layer`: The storage layer supports SQL, Purview(Atlas). The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI layer`: The Web UI for feature registry. Written in React with a few UI frameworks.

**Comment by windoze** [comment]
The issue is caused by a dependency version mismatch between Feathr core and DataBricks Runtime.
The Feathr core uses Google ProtoBuf 3 to encode Redis values but DataBricks provides ProtoBuf 2 in their runtime environment.
 
This bug will happen when:
* Running Feathr jobs on DataBricks, and,
* Using Redis as the output sink, and,
* Using Jar from Maven instead of local or other sources.
 
NOTE: The bug will *not* be triggered if the job uses the fat JAR, it only affects Maven JAR because the JAR from Maven doesn’t include its dependencies inside of the JAR file, it relies on the environment to provide/resolve dependencies.
 
The workaround is to use the fat JAR, either from our public storage, or user can build one by themselves.
 
One possible solution is to downgrade the version of the ProtoBuf to 2 in Feathr core, I did some preliminary tests and found it should work, but we still need wider tests to confirm all related functionalities.

**Comment by hangfei** [comment]
Thanks for debugging and sharing your insights.

Let are some incompatibilities between 2 and 3. Before switching, we should figure out those.

Besides, was wondering if anyone know any way to keep 3 even the cluster is using 2?

This might be a backward incompatible changes for people who already pushed data to redis with 3.

We should also think about what's our strategy in the future when the cluster start to use 3.

**Comment by blrchen** [comment]
Lower feathr runtime protobuf version from 3 to 2 is one option, i am bringing some other options for discussion
- Include protobuf 3 into feathr runtime jar. 
- Not use protobuf, just save json string to redis. Actually for other store like cosmos db, aerospike, protobuf is not used, same applies to Elastic Search which is coming soon. Probably there some known limitation in Redis that we have to use protobuf, pls let me know.

i agree on backward incompatible issues, we should make sure existing data written by protobuf3 can still be consumed. 

cc @xiaoyongzhu

**Comment by hangfei** [comment]
@blrchen those are good options we can consider.

Redis, and some other databases, only supported primitive data types whereas Feathr has richer data types, like list and map. So encoding is needed here. We can also use other encoding libs, like Avro, but the same version incompatiblity may exist. In LinkedIn, we use Avro and we also face the same issue. For avro, i remember we have a compatibility layer to convert between 1.4 and 1.7. It seems possible for protobuf 2 and 3 as well.

Do you save json to cosmos db? I am not sure if the performance is optimal though. If that's the recommended approach, that should be fine. If not, we can conduct some study to figure out the optimal encoding we want to use.
